/*
 * Copyright (C) 2008  Bernhard Hobiger
 *
 * This file is part of HoDoKu.
 *
 * HoDoKu is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * HoDoKu is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with HoDoKu. If not, see <http://www.gnu.org/licenses/>.
 */

package sudoku;

/**
 *
 * @author  zhobigbe
 */
public class ConfigStepPanel extends javax.swing.JPanel {

    private static String[] finSizes = { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" };
    private static String[] chainSizes = {
        "0",  "1",  "2",  "3",  "4",  "5",  "6",  "7",  "8",  "9",
        "10", "11", "12", "13", "14", "15", "16", "17", "18", "19",
        "20", "21", "22", "23", "24", "25", "26", "27", "28", "29",
        "30", "31", "32", "33", "34", "35", "36", "37", "38", "39"
    };
    
    /** Creates new form ConfigStepPanel */
    public ConfigStepPanel() {
        initComponents();
        
        for (int i = 0; i < finSizes.length; i++) {
            maxFinsComboBox.addItem(finSizes[i]);
            maxEndoFinsComboBox.addItem(finSizes[i]);
        }
        
        for (int i = 0; i < chainSizes.length; i++) {
            restrictChainSizeComboBox.addItem(chainSizes[i]);
            restrictNiceLoopSizeComboBox.addItem(chainSizes[i]);
        }
        
        NumbersOnlyDocument doc = new NumbersOnlyDocument();
        maxTableEntryLengthTextField.setDocument(doc);
        doc = new NumbersOnlyDocument();
        lookAheadTextField.setDocument(doc);

        // Alle Werte aus den Default-Optionen setzen
        initAll(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fishPanel = new javax.swing.JPanel();
        maxFinsLabel = new javax.swing.JLabel();
        maxEndoFinsLabel = new javax.swing.JLabel();
        maxFinsComboBox = new javax.swing.JComboBox();
        maxEndoFinsComboBox = new javax.swing.JComboBox();
        checkTemplatesCheckBox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        restrictChainSizeLabel = new javax.swing.JLabel();
        restrictNiceLoopSizeLabel = new javax.swing.JLabel();
        restrictChainSizeComboBox = new javax.swing.JComboBox();
        restrictNiceLoopSizeComboBox = new javax.swing.JComboBox();
        restrictChainSizeCheckBox = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        resetButton = new javax.swing.JButton();
        tablingPanel = new javax.swing.JPanel();
        maxTableEntryLengthLabel = new javax.swing.JLabel();
        lookAheadLabel = new javax.swing.JLabel();
        maxTableEntryLengthTextField = new javax.swing.JTextField();
        lookAheadTextField = new javax.swing.JTextField();
        onlyOneChainCheckBox = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        useZeroInsteadOfDotCheckBox = new javax.swing.JCheckBox();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("intl/ConfigStepPanel"); // NOI18N
        fishPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ConfigStepPanel.fishPanel.border.title"))); // NOI18N

        maxFinsLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigStepPanel").getString("ConfigStepPanel.maxFinsLabel.mnemonic").charAt(0));
        maxFinsLabel.setText(bundle.getString("ConfigStepPanel.maxFinsLabel.text")); // NOI18N

        maxEndoFinsLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigStepPanel").getString("ConfigStepPanel.maxEndoFinsLabel.mnemonic").charAt(0));
        maxEndoFinsLabel.setText(bundle.getString("ConfigStepPanel.maxEndoFinsLabel.text")); // NOI18N

        checkTemplatesCheckBox.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigStepPanel").getString("ConfigStepPanel.checkTemplatesCheckBox.mnemonic").charAt(0));
        checkTemplatesCheckBox.setText(bundle.getString("ConfigStepPanel.checkTemplatesCheckBox.text")); // NOI18N
        checkTemplatesCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        checkTemplatesCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout fishPanelLayout = new javax.swing.GroupLayout(fishPanel);
        fishPanel.setLayout(fishPanelLayout);
        fishPanelLayout.setHorizontalGroup(
            fishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fishPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkTemplatesCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addGroup(fishPanelLayout.createSequentialGroup()
                        .addGroup(fishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fishPanelLayout.createSequentialGroup()
                                .addComponent(maxFinsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addGap(28, 28, 28))
                            .addComponent(maxEndoFinsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxFinsComboBox, 0, 81, Short.MAX_VALUE)
                            .addComponent(maxEndoFinsComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        fishPanelLayout.setVerticalGroup(
            fishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fishPanelLayout.createSequentialGroup()
                .addGroup(fishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxFinsLabel)
                    .addComponent(maxFinsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxEndoFinsLabel)
                    .addComponent(maxEndoFinsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkTemplatesCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ConfigStepPanel.jPanel3.border.title"))); // NOI18N

        restrictChainSizeLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigStepPanel").getString("ConfigStepPanel.restrictChainSizeLabel.mnemonic").charAt(0));
        restrictChainSizeLabel.setText(bundle.getString("ConfigStepPanel.restrictChainSizeLabel.text")); // NOI18N

        restrictNiceLoopSizeLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigStepPanel").getString("ConfigStepPanel.restrictNiceLoopSizeLabel.mnemonic").charAt(0));
        restrictNiceLoopSizeLabel.setText(bundle.getString("ConfigStepPanel.restrictNiceLoopSizeLabel.text")); // NOI18N

        restrictChainSizeCheckBox.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigStepPanel").getString("ConfigStepPanel.restrictChainSizeCheckBox.mnemonic").charAt(0));
        restrictChainSizeCheckBox.setText(bundle.getString("ConfigStepPanel.restrictChainSizeCheckBox.text")); // NOI18N
        restrictChainSizeCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        restrictChainSizeCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(restrictChainSizeLabel)
                            .addComponent(restrictNiceLoopSizeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(restrictChainSizeComboBox, 0, 73, Short.MAX_VALUE)
                            .addComponent(restrictNiceLoopSizeComboBox, 0, 73, Short.MAX_VALUE)))
                    .addComponent(restrictChainSizeCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restrictChainSizeLabel)
                    .addComponent(restrictChainSizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(restrictNiceLoopSizeLabel)
                    .addComponent(restrictNiceLoopSizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(restrictChainSizeCheckBox)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fishPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(fishPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        resetButton.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigStepPanel").getString("ConfigStepPanel.resetButton.mnemonic").charAt(0));
        resetButton.setText(bundle.getString("ConfigStepPanel.resetButton.text")); // NOI18N
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        tablingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ConfigStepPanel.tablingPanel.border.title"))); // NOI18N

        maxTableEntryLengthLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigStepPanel").getString("ConfigStepPanel.maxTableEntryLengthLabel.mnemonic").charAt(0));
        maxTableEntryLengthLabel.setLabelFor(maxTableEntryLengthTextField);
        maxTableEntryLengthLabel.setText(bundle.getString("ConfigStepPanel.maxTableEntryLengthLabel.text")); // NOI18N

        lookAheadLabel.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigStepPanel").getString("ConfigStepPanel.lookAheadLabel.mnemonic").charAt(0));
        lookAheadLabel.setLabelFor(lookAheadTextField);
        lookAheadLabel.setText(bundle.getString("ConfigStepPanel.lookAheadLabel.text")); // NOI18N

        onlyOneChainCheckBox.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigStepPanel").getString("ConfigStepPanel.onlyOneChainCheckBox.mnemonic").charAt(0));
        onlyOneChainCheckBox.setText(bundle.getString("ConfigStepPanel.onlyOneChainCheckBox.text")); // NOI18N
        onlyOneChainCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        onlyOneChainCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout tablingPanelLayout = new javax.swing.GroupLayout(tablingPanel);
        tablingPanel.setLayout(tablingPanelLayout);
        tablingPanelLayout.setHorizontalGroup(
            tablingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablingPanelLayout.createSequentialGroup()
                .addGroup(tablingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tablingPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tablingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxTableEntryLengthLabel)
                            .addComponent(lookAheadLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tablingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lookAheadTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(maxTableEntryLengthTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                    .addGroup(tablingPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(onlyOneChainCheckBox)))
                .addContainerGap())
        );
        tablingPanelLayout.setVerticalGroup(
            tablingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablingPanelLayout.createSequentialGroup()
                .addGroup(tablingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maxTableEntryLengthLabel)
                    .addComponent(maxTableEntryLengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lookAheadLabel)
                    .addComponent(lookAheadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(onlyOneChainCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ConfigStepPanel.jPanel4.border.title"))); // NOI18N

        useZeroInsteadOfDotCheckBox.setMnemonic(java.util.ResourceBundle.getBundle("intl/ConfigStepPanel").getString("ConfigStepPanel.useZeroInsteadOfDotCheckBox.mnemonic").charAt(0));
        useZeroInsteadOfDotCheckBox.setText(bundle.getString("ConfigStepPanel.useZeroInsteadOfDotCheckBox.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(useZeroInsteadOfDotCheckBox)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(useZeroInsteadOfDotCheckBox)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tablingPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(132, Short.MAX_VALUE)
                        .addComponent(resetButton)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(tablingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(resetButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        initAll(true);
    }//GEN-LAST:event_resetButtonActionPerformed
    
    public void okPressed() {
        // Alle Werte übernehmen
        Options.getInstance().maxFins = Integer.parseInt((String)maxFinsComboBox.getSelectedItem());
        Options.getInstance().maxEndoFins = Integer.parseInt((String)maxEndoFinsComboBox.getSelectedItem());
        Options.getInstance().checkTemplates = checkTemplatesCheckBox.isSelected();
        
        Options.getInstance().restrictChainLength = Integer.parseInt((String)restrictChainSizeComboBox.getSelectedItem());
        Options.getInstance().restrictNiceLoopLength = Integer.parseInt((String)restrictNiceLoopSizeComboBox.getSelectedItem());
        Options.getInstance().restrictChainSize = restrictChainSizeCheckBox.isSelected();

        Options.getInstance().maxTableEntryLength = Integer.parseInt(maxTableEntryLengthTextField.getText());
        Options.getInstance().anzTableLookAhead = Integer.parseInt(lookAheadTextField.getText());
        Options.getInstance().onlyOneChainPerStep = onlyOneChainCheckBox.isSelected();
        
        Options.getInstance().useZeroInsteadOfDot = useZeroInsteadOfDotCheckBox.isSelected();
    }
    
    private void initAll(boolean setDefault) {
        if (setDefault) {
            maxFinsComboBox.setSelectedIndex(Options.MAX_FINS);
            maxEndoFinsComboBox.setSelectedIndex(Options.MAX_ENDO_FINS);
            checkTemplatesCheckBox.setSelected(Options.CHECK_TEMPLATES);
            
            restrictChainSizeComboBox.setSelectedIndex(Options.RESTRICT_CHAIN_LENGTH);
            restrictNiceLoopSizeComboBox.setSelectedIndex(Options.RESTRICT_NICE_LOOP_LENGTH);
            restrictChainSizeCheckBox.setSelected(Options.RESTRICT_CHAIN_SIZE);
            
            maxTableEntryLengthTextField.setText(Integer.toString(Options.MAX_TABLE_ENTRY_LENGTH));
            lookAheadTextField.setText(Integer.toString(Options.ANZ_TABLE_LOOK_AHEAD));
            onlyOneChainCheckBox.setSelected(Options.ONLY_ONE_CHAIN_PER_STEP);
            
            useZeroInsteadOfDotCheckBox.setSelected(Options.USE_ZERO_INSTEAD_OF_DOT);
        } else {
            maxFinsComboBox.setSelectedIndex(Options.getInstance().maxFins);
            maxEndoFinsComboBox.setSelectedIndex(Options.getInstance().maxEndoFins);
            checkTemplatesCheckBox.setSelected(Options.getInstance().checkTemplates);
            
            restrictChainSizeComboBox.setSelectedIndex(Options.getInstance().restrictChainLength);
            restrictNiceLoopSizeComboBox.setSelectedIndex(Options.getInstance().restrictNiceLoopLength);
            restrictChainSizeCheckBox.setSelected(Options.getInstance().restrictChainSize);
            
            maxTableEntryLengthTextField.setText(Integer.toString(Options.getInstance().maxTableEntryLength));
            lookAheadTextField.setText(Integer.toString(Options.getInstance().anzTableLookAhead));
            onlyOneChainCheckBox.setSelected(Options.getInstance().onlyOneChainPerStep);
            
            useZeroInsteadOfDotCheckBox.setSelected(Options.getInstance().useZeroInsteadOfDot);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkTemplatesCheckBox;
    private javax.swing.JPanel fishPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lookAheadLabel;
    private javax.swing.JTextField lookAheadTextField;
    private javax.swing.JComboBox maxEndoFinsComboBox;
    private javax.swing.JLabel maxEndoFinsLabel;
    private javax.swing.JComboBox maxFinsComboBox;
    private javax.swing.JLabel maxFinsLabel;
    private javax.swing.JLabel maxTableEntryLengthLabel;
    private javax.swing.JTextField maxTableEntryLengthTextField;
    private javax.swing.JCheckBox onlyOneChainCheckBox;
    private javax.swing.JButton resetButton;
    private javax.swing.JCheckBox restrictChainSizeCheckBox;
    private javax.swing.JComboBox restrictChainSizeComboBox;
    private javax.swing.JLabel restrictChainSizeLabel;
    private javax.swing.JComboBox restrictNiceLoopSizeComboBox;
    private javax.swing.JLabel restrictNiceLoopSizeLabel;
    private javax.swing.JPanel tablingPanel;
    private javax.swing.JCheckBox useZeroInsteadOfDotCheckBox;
    // End of variables declaration//GEN-END:variables
    
}
