/*
 * Copyright (C) 2008  Bernhard Hobiger
 *
 * This file is part of HoDoKu.
 *
 * HoDoKu is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * HoDoKu is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with HoDoKu. If not, see <http://www.gnu.org/licenses/>.
 */

package sudoku;

import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author  Bernhard Hobiger
 */
public class FindAllStepsProgressDialog extends javax.swing.JDialog implements Runnable {
    private static final int MAX_STEPS = 18;
    
    private List<SolutionStep> steps;
    private Sudoku sudoku;
    private int minSize;
    private int maxSize;
    private int maxFins;
    private int maxEndoFins;
    private Thread thread;
    private boolean forcingChains;
    private boolean forcingNets;
    
    private static SimpleSolver solver1 = new SimpleSolver();
    private static SingleDigitPatternSolver solver2 = new SingleDigitPatternSolver();
    private static MiscellaneousSolver solver3 = new MiscellaneousSolver();
    private static FishSolver solver4 = new FishSolver();
    private static UniquenessSolver solver5 = new UniquenessSolver();
    private static WingSolver solver6 = new WingSolver();
    private static ColoringSolver solver7 = new ColoringSolver();
    private static ChainSolver solver8 = new ChainSolver();
    private static TemplateSolver solver9 = new TemplateSolver();
    private static AlsSolver solver10 = new AlsSolver();
    private static TablingSolver solver11 = new TablingSolver();
    
    /** Creates new form FindAllStepsProgressDialog */
    public FindAllStepsProgressDialog(java.awt.Frame parent, boolean modal, Sudoku sudoku,
            int minSize, int maxSize, int maxFins, int maxEndoFins,
            boolean forcingChains, boolean forcingNets) {
        super(parent, modal);
        
        this.sudoku = sudoku;
        this.minSize = minSize;
        this.maxSize = maxSize;
        this.maxFins = maxFins;
        this.maxEndoFins = maxEndoFins;
        this.forcingChains = forcingChains;
        this.forcingNets = forcingNets;
        
        initComponents();
        getRootPane().setDefaultButton(abbrechenButton);
        KeyStroke escapeKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false);
        Action escapeAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible( false );
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escapeKeyStroke, "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", escapeAction);
        
        progressBar.setMinimum(0);
        progressBar.setMaximum(MAX_STEPS);
        progressBar.setValue(0);
        
        thread = new Thread(this);
        thread.start();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        abbrechenButton = new javax.swing.JButton();
        fishProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("intl/FindAllStepsProgressDialog"); // NOI18N
        setTitle(bundle.getString("FindAllStepsProgressDialog.title")); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        progressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        progressLabel.setText(bundle.getString("FindAllStepsProgressDialog.progressLabel.text")); // NOI18N

        progressBar.setStringPainted(true);

        abbrechenButton.setMnemonic(java.util.ResourceBundle.getBundle("intl/FindAllStepsProgressDialog").getString("FindAllStepsProgressDialog.abbrechenButton.mnemonic").charAt(0));
        abbrechenButton.setText(bundle.getString("FindAllStepsProgressDialog.abbrechenButton.text")); // NOI18N
        abbrechenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abbrechenButtonActionPerformed(evt);
            }
        });

        fishProgressBar.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(progressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(abbrechenButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fishProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fishProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(abbrechenButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        abbrechenButtonActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing
    
    private void abbrechenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abbrechenButtonActionPerformed
        thread.interrupt();
        try {
            thread.join();
        } catch (InterruptedException ex) {
            Logger.getLogger(getClass().getName()).log(Level.SEVERE, "Interrupted while waiting for AllSteps-thread", ex);
        }
        sudoku = null;
        setVisible(false);
    }//GEN-LAST:event_abbrechenButtonActionPerformed
    
    private void updateProgress(final String label, final int step) {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                progressLabel.setText(java.util.ResourceBundle.getBundle("intl/FindAllStepsProgressDialog").getString("FindAllStepsProgressDialog.searching") + " " + label);
                progressBar.setValue(step);
            }
        });
    }
    
    @Override
    public void run() {
        int actStep = 0;
        //boolean[] tmpCands = new boolean[9];
        List<SolutionStep> steps1 = null;
        while (! thread.isInterrupted()) {
            switch (actStep) {
                case 0:
                    updateProgress(java.util.ResourceBundle.getBundle("intl/FindAllStepsProgressDialog").getString("FindAllStepsProgressDialog.simple_solutions"), actStep);
                    steps = solver1.findAllFullHouses(sudoku);
                    steps1 = solver1.findAllHiddenXle(sudoku);
                    steps.addAll(steps1);
                    steps1 = solver1.findAllNakedXle(sudoku);
                    steps.addAll(steps1);
                    steps1 = solver1.findAllLockedCandidates(sudoku);
                    steps.addAll(steps1);
                    steps1 = solver2.findAllSkyScrapers(sudoku);
                    steps.addAll(steps1);
                    steps1 = solver2.findAllEmptyRectangles(sudoku);
                    steps.addAll(steps1);
                    steps1 = solver2.findAllTwoStringKites(sudoku);
                    steps.addAll(steps1);
                    steps1 = solver3.getAllSueDeCoqs(sudoku);
                    steps.addAll(steps1);
                    break;
                case 1:
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                    updateProgress(java.util.ResourceBundle.getBundle("intl/FindAllStepsProgressDialog").getString("FindAllStepsProgressDialog.fish") + " " + actStep, actStep);
                    steps1 = solver4.getAllFishes(sudoku, minSize, maxSize, maxFins, maxEndoFins, this, actStep);
                    steps.addAll(steps1);
                    break;
                case 10:
                    updateProgress(java.util.ResourceBundle.getBundle("intl/FindAllStepsProgressDialog").getString("FindAllStepsProgressDialog.uniqueness"), actStep);
                    steps1 = solver5.getAllUniqueness(sudoku);
                    steps.addAll(steps1);
                    steps1 = solver6.getAllWings(sudoku);
                    steps.addAll(steps1);
                    steps1 = solver7.findAllSimpleColors(sudoku);
                    steps.addAll(steps1);
                    steps1 = solver7.findAllMultiColors(sudoku);
                    steps.addAll(steps1);
                    break;
                case 11:
                    updateProgress(java.util.ResourceBundle.getBundle("intl/FindAllStepsProgressDialog").getString("FindAllStepsProgressDialog.chains"), actStep);
                    steps1 = solver8.getAllChains(sudoku);
                    steps.addAll(steps1);
                    break;
                case 12:
                    updateProgress(java.util.ResourceBundle.getBundle("intl/FindAllStepsProgressDialog").getString("FindAllStepsProgressDialog.nice_loops"), actStep);
                    steps1 = solver11.getAllNiceLoops(sudoku);
                    steps.addAll(steps1);
                    break;
                case 13:
                    updateProgress(java.util.ResourceBundle.getBundle("intl/FindAllStepsProgressDialog").getString("FindAllStepsProgressDialog.grouped_nice_loops"), actStep);
                    steps1 = solver11.getAllGroupedNiceLoops(sudoku);
                    steps.addAll(steps1);
                    break;
                case 14:
                    updateProgress(java.util.ResourceBundle.getBundle("intl/FindAllStepsProgressDialog").getString("FindAllStepsProgressDialog.templates"), actStep);
                    steps1 = solver9.getAllTemplates(sudoku);
                    steps.addAll(steps1);
                    break;
                case 15:
                    updateProgress(java.util.ResourceBundle.getBundle("intl/FindAllStepsProgressDialog").getString("FindAllStepsProgressDialog.als"), actStep);
                    steps1 = solver10.getAllAlses(sudoku);
                    steps.addAll(steps1);
                    break;
                case 16:
                    if (forcingChains) {
                        updateProgress(java.util.ResourceBundle.getBundle("intl/FindAllStepsProgressDialog").getString("FindAllStepsProgressDialog.forcing_Chains"), actStep);
                        steps1 = solver11.getAllForcingChains(sudoku);
                        steps.addAll(steps1);
                    }
                    break;
                case 17:
                    if (forcingNets) {
                        updateProgress(java.util.ResourceBundle.getBundle("intl/FindAllStepsProgressDialog").getString("FindAllStepsProgressDialog.forcing_Nets"), actStep);
                        steps1 = solver11.getAllForcingNets(sudoku);
                        steps.addAll(steps1);
                    }
                    break;
            }
            actStep++;
            if (actStep >= MAX_STEPS) {
                break;
            }
        }
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                setVisible(false);
            }
        });
    }
    
    public void resetFishProgressBar(final int maxValue) {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                fishProgressBar.setMaximum(maxValue);
                fishProgressBar.setValue(0);
            }
        });
    }
    
    public void updateFishProgressBar(final int actValue) {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                fishProgressBar.setValue(actValue);
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FindAllStepsProgressDialog(new javax.swing.JFrame(), true, null, 0, 0, 0, 0, false, false).setVisible(true);
            }
        });
    }
    
    public List<SolutionStep> getSteps() {
        return steps;
    }
    
    public int getMaxSteps() {
        return MAX_STEPS;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abbrechenButton;
    private javax.swing.JProgressBar fishProgressBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressLabel;
    // End of variables declaration//GEN-END:variables
    
}
